// Location data with vibe colors and predefined coordinates
const locationData = [
  // Dehradun and Mussoorie locations
  { name: "Pacific Mall Dehradun", vibe: "Shopping, Party", time: "5 PM to 10 PM", features: "Shopping, Multiplex, Cafes, Restaurants", intensity: 0.8, color: '#FFD700', lat: 30.3165, lng: 78.0322, type: 'market' },
  { name: "Clock Tower Dehradun", vibe: "Historical, Market", time: "10 AM to 7 PM", features: "Historical Site, Crowded Market", intensity: 0.7, color: '#8B4513', lat: 30.3175, lng: 78.0332, type: 'market' },
  { name: "Sahasradhara Dehradun", vibe: "Natural, Peaceful", time: "6 AM to 12 PM", features: "Waterfall, Caves, Scenic Beauty", intensity: 0.6, color: '#228B22', lat: 30.3265, lng: 78.0422, type: 'natural' },
  { name: "Kempty Falls Mussoorie", vibe: "Adventure, Family", time: "9 AM to 5 PM", features: "Waterfall, Picnic Spot, Family-Friendly", intensity: 0.7, color: '#FF4500', lat: 30.4567, lng: 78.0789, type: 'adventure' },
  { name: "Mussoorie Mall Road", vibe: "Hill Station, Romantic", time: "8 AM to 6 PM", features: "Hill Station, Peaceful, Romantic Spot", intensity: 0.9, color: '#FF69B4', lat: 30.4467, lng: 78.0689, type: 'hillstation' },
  { name: "Dhanaulti Mussoorie", vibe: "Himalayan, Couples", time: "10 AM to 5 PM (Winter)", features: "Snowfall, Peaceful Environment, Couples", intensity: 0.8, color: '#4169E1', lat: 30.4367, lng: 78.0589, type: 'hillstation' },
  { name: "Rajaji National Park Dehradun", vibe: "Wildlife, Natural", time: "6 AM to 6 PM", features: "Safari, Natural Beauty", intensity: 0.7, color: '#006400', lat: 30.3065, lng: 78.0222, type: 'wildlife' },
  { name: "Robbers Cave Dehradun", vibe: "Adventure, Family", time: "9 AM to 5 PM", features: "Cave, Waterfall, Picnic Spot", intensity: 0.6, color: '#FF4500', lat: 30.3600, lng: 78.0620, type: 'adventure' },
  { name: "Tapkeshwar Temple Dehradun", vibe: "Religious, Peaceful", time: "6 AM to 7 PM", features: "Shiva Temple, Natural Caves, Peaceful", intensity: 0.5, color: '#FFA500', lat: 30.3094, lng: 78.0480, type: 'temple' },
  { name: "Lachhiwala Nature Park Dehradun", vibe: "Natural, Family", time: "8 AM to 6 PM", features: "Lake, Picnic Spot, Kids-Friendly", intensity: 0.6, color: '#32CD32', lat: 30.3465, lng: 78.0089, type: 'natural' },
  { name: "Forest Research Institute Dehradun", vibe: "Historical, Educational", time: "9 AM to 5 PM", features: "Colonial Architecture, Museum, Gardens", intensity: 0.8, color: '#8B4513', lat: 30.3465, lng: 78.0089, type: 'natural' },
  { name: "Mindrolling Monastery Dehradun", vibe: "Religious, Peaceful", time: "6 AM to 6 PM", features: "Buddhist Monastery, Peaceful Environment", intensity: 0.6, color: '#FFA500', lat: 30.2911, lng: 77.9911, type: 'temple' },
  { name: "Dehradun Zoo", vibe: "Family, Educational", time: "9 AM to 5 PM", features: "Wildlife, Kids Activities, Nature", intensity: 0.7, color: '#32CD32', lat: 30.3211, lng: 78.0411, type: 'wildlife' },
  { name: "Malsi Deer Park Dehradun", vibe: "Natural, Family", time: "8 AM to 6 PM", features: "Deer Park, Nature Trails, Picnic", intensity: 0.6, color: '#32CD32', lat: 30.3811, lng: 78.0511, type: 'natural' },
  { name: "George Everest House Mussoorie", vibe: "Historical, Adventure", time: "9 AM to 5 PM", features: "Historical Site, Trekking, Views", intensity: 0.7, color: '#8B4513', lat: 30.4511, lng: 78.0611, type: 'hillstation' },
  { name: "Cloud End Mussoorie", vibe: "Hill Station, Romantic", time: "8 AM to 6 PM", features: "Tea Gardens, Scenic Views, Peaceful", intensity: 0.8, color: '#FF69B4', lat: 30.4611, lng: 78.0711, type: 'hillstation' },
  { name: "Jharipani Falls Mussoorie", vibe: "Adventure, Natural", time: "9 AM to 5 PM", features: "Waterfall, Trekking, Nature", intensity: 0.7, color: '#FF4500', lat: 30.4711, lng: 78.0811, type: 'adventure' },
  { name: "Buddha Temple Dehradun", vibe: "Religious, Peaceful", time: "6 AM to 7 PM", features: "Buddhist Temple, Meditation, Peaceful", intensity: 0.6, color: '#FFA500', lat: 30.3211, lng: 78.0211, type: 'temple' },
  { name: "Dehradun Cantt", vibe: "Historical, Shopping", time: "10 AM to 8 PM", features: "Military Area, Shopping, Cafes", intensity: 0.7, color: '#8B4513', lat: 30.3311, lng: 78.0311, type: 'market' },
  { name: "Rajpur Road Dehradun", vibe: "Shopping, Party", time: "10 AM to 10 PM", features: "Shopping, Restaurants, Nightlife", intensity: 0.8, color: '#FFD700', lat: 30.3411, lng: 78.0411, type: 'market' },

  // Famous places from other parts of Uttarakhand
  { name: "Kedarnath Temple", vibe: "Religious, Spiritual", time: "4 AM to 9 PM", features: "Temple, Trekking, Spiritual Experience", intensity: 0.9, color: '#FFA500', lat: 30.7344, lng: 79.0669, type: 'temple' },
  { name: "Badrinath Temple", vibe: "Religious, Spiritual", time: "4 AM to 9 PM", features: "Temple, Hot Springs, Spiritual Experience", intensity: 0.9, color: '#FFA500', lat: 30.7444, lng: 79.4944, type: 'temple' },
  { name: "Gangotri Temple", vibe: "Religious, Natural", time: "6 AM to 8 PM", features: "Temple, River, Scenic Beauty", intensity: 0.8, color: '#FFA500', lat: 30.9944, lng: 78.9444, type: 'temple' },
  { name: "Yamunotri Temple", vibe: "Religious, Natural", time: "6 AM to 8 PM", features: "Temple, Hot Springs, Trekking", intensity: 0.8, color: '#FFA500', lat: 31.0144, lng: 78.4544, type: 'temple' },
  { name: "Nainital Lake", vibe: "Hill Station, Romantic", time: "6 AM to 6 PM", features: "Lake, Boating, Scenic Views", intensity: 0.9, color: '#FF69B4', lat: 29.3944, lng: 79.4544, type: 'hillstation' },
  { name: "Jim Corbett National Park", vibe: "Wildlife, Adventure", time: "6 AM to 6 PM", features: "Safari, Wildlife, Nature", intensity: 0.9, color: '#006400', lat: 29.5444, lng: 78.9444, type: 'wildlife' },
  { name: "Valley of Flowers", vibe: "Natural, Adventure", time: "8 AM to 5 PM", features: "Flowers, Trekking, Photography", intensity: 0.8, color: '#228B22', lat: 30.7344, lng: 79.6444, type: 'natural' },
  { name: "Hemkund Sahib", vibe: "Religious, Adventure", time: "6 AM to 5 PM", features: "Gurudwara, Lake, Trekking", intensity: 0.8, color: '#FFA500', lat: 30.6844, lng: 79.6144, type: 'temple' },
  { name: "Rishikesh", vibe: "Spiritual, Adventure", time: "6 AM to 8 PM", features: "Temples, River Rafting, Yoga", intensity: 0.9, color: '#4169E1', lat: 30.0844, lng: 78.2644, type: 'adventure' },
  { name: "Haridwar", vibe: "Religious, Cultural", time: "4 AM to 10 PM", features: "Ganga Aarti, Temples, Culture", intensity: 0.9, color: '#FFA500', lat: 29.9444, lng: 78.1644, type: 'temple' },
  { name: "Auli", vibe: "Adventure, Romantic", time: "8 AM to 5 PM", features: "Skiing, Trekking, Scenic Views", intensity: 0.8, color: '#FF4500', lat: 30.5444, lng: 79.5644, type: 'adventure' },
  { name: "Chopta", vibe: "Adventure, Natural", time: "6 AM to 6 PM", features: "Trekking, Camping, Nature", intensity: 0.7, color: '#228B22', lat: 30.4444, lng: 79.2144, type: 'adventure' },
  { name: "Almora", vibe: "Cultural, Historical", time: "8 AM to 6 PM", features: "Temples, Culture, Views", intensity: 0.7, color: '#8B4513', lat: 29.5944, lng: 79.6544, type: 'hillstation' },
  { name: "Ranikhet", vibe: "Hill Station, Peaceful", time: "8 AM to 6 PM", features: "Army Cantonment, Views, Peaceful", intensity: 0.7, color: '#FF69B4', lat: 29.6444, lng: 79.4244, type: 'hillstation' },
  { name: "Binsar", vibe: "Wildlife, Natural", time: "6 AM to 6 PM", features: "Wildlife Sanctuary, Views, Nature", intensity: 0.6, color: '#006400', lat: 29.7444, lng: 79.7644, type: 'wildlife' },
  { name: "Kausani", vibe: "Hill Station, Romantic", time: "6 AM to 6 PM", features: "Tea Gardens, Views, Peaceful", intensity: 0.7, color: '#FF69B4', lat: 29.8444, lng: 79.6144, type: 'hillstation' },
  { name: "Mukteshwar", vibe: "Adventure, Natural", time: "6 AM to 6 PM", features: "Trekking, Views, Nature", intensity: 0.6, color: '#228B22', lat: 29.4744, lng: 79.6444, type: 'adventure' },
  { name: "Pithoragarh", vibe: "Historical, Natural", time: "6 AM to 6 PM", features: "Fort, Views, Culture", intensity: 0.6, color: '#8B4513', lat: 29.5844, lng: 80.2144, type: 'natural' },
  { name: "Bageshwar", vibe: "Religious, Natural", time: "6 AM to 6 PM", features: "Temples, River, Nature", intensity: 0.5, color: '#FFA500', lat: 29.8444, lng: 79.7744, type: 'temple' },
  { name: "Champawat", vibe: "Historical, Cultural", time: "6 AM to 6 PM", features: "Temples, History, Culture", intensity: 0.5, color: '#8B4513', lat: 29.3344, lng: 80.0944, type: 'temple' },

  // Adding travel-related places
  { name: "Dehradun Railway Station", vibe: "Travel, Transport", time: "24/7", features: "Train Station, Food Court, Parking", intensity: 0.8, color: '#4169E1', lat: 30.3211, lng: 78.0311, type: 'travel', minZoom: 14 },
  { name: "Jolly Grant Airport", vibe: "Travel, Transport", time: "24/7", features: "Airport, Taxi Service, Food Court", intensity: 0.9, color: '#4169E1', lat: 30.1897, lng: 78.1803, type: 'travel', minZoom: 14 },
  { name: "ISBT Dehradun", vibe: "Travel, Transport", time: "24/7", features: "Bus Station, Food Court, Parking", intensity: 0.8, color: '#4169E1', lat: 30.3311, lng: 78.0411, type: 'travel', minZoom: 14 },
  { name: "Mussoorie Bus Stand", vibe: "Travel, Transport", time: "6 AM to 8 PM", features: "Bus Station, Taxi Stand, Food", intensity: 0.7, color: '#4169E1', lat: 30.4511, lng: 78.0611, type: 'travel', minZoom: 14 },
  { name: "Hotel Madhuban", vibe: "Accommodation, Luxury", time: "24/7", features: "Hotel, Restaurant, Spa", intensity: 0.8, color: '#FFD700', lat: 30.3411, lng: 78.0411, type: 'hotel', minZoom: 14 },
  { name: "Hotel Madira", vibe: "Accommodation, Family", time: "24/7", features: "Hotel, Restaurant, Conference Hall", intensity: 0.7, color: '#FFD700', lat: 30.3311, lng: 78.0311, type: 'hotel', minZoom: 14 },
  { name: "Hotel President", vibe: "Accommodation, Luxury", time: "24/7", features: "Hotel, Restaurant, Pool", intensity: 0.9, color: '#FFD700', lat: 30.3211, lng: 78.0211, type: 'hotel', minZoom: 14 },
  { name: "Hotel Madhuban Mussoorie", vibe: "Accommodation, Luxury", time: "24/7", features: "Hotel, Restaurant, Views", intensity: 0.8, color: '#FFD700', lat: 30.4511, lng: 78.0611, type: 'hotel', minZoom: 14 },
  { name: "Hotel Padmini", vibe: "Accommodation, Family", time: "24/7", features: "Hotel, Restaurant, Garden", intensity: 0.7, color: '#FFD700', lat: 30.4611, lng: 78.0711, type: 'hotel', minZoom: 14 },
  { name: "Hotel Palace Heights", vibe: "Accommodation, Luxury", time: "24/7", features: "Hotel, Restaurant, Spa", intensity: 0.8, color: '#FFD700', lat: 30.4711, lng: 78.0811, type: 'hotel', minZoom: 14 },

  // Reorganizing cafes with new coordinates
  { name: "Cafe Coffee Day Rajpur Road", vibe: "Cafe, Relaxed", time: "8 AM to 10 PM", features: "Coffee, Snacks, WiFi", intensity: 0.6, color: '#8B4513', lat: 30.3421, lng: 78.0421, type: 'cafe', minZoom: 14 },
  { name: "Starbucks Dehradun", vibe: "Cafe, Relaxed", time: "7 AM to 10 PM", features: "Coffee, Snacks, WiFi", intensity: 0.6, color: '#8B4513', lat: 30.3431, lng: 78.0431, type: 'cafe', minZoom: 14 },
  { name: "Ellora's Melting Moments", vibe: "Cafe, Romantic", time: "10 AM to 9 PM", features: "Bakery, Coffee, Desserts", intensity: 0.6, color: '#8B4513', lat: 30.3441, lng: 78.0441, type: 'cafe', minZoom: 14 },
  { name: "Cafe Dehradun", vibe: "Cafe, Party", time: "9 AM to 11 PM", features: "Live Music, Food, Drinks", intensity: 0.8, color: '#8B4513', lat: 30.3451, lng: 78.0451, type: 'cafe', minZoom: 14 },
  { name: "Urban Cafe", vibe: "Cafe, Party", time: "10 AM to 11 PM", features: "Fusion Food, Live Music", intensity: 0.8, color: '#8B4513', lat: 30.3461, lng: 78.0461, type: 'cafe', minZoom: 14 },

  // Reorganizing restaurants with new coordinates
  { name: "Kalsang Restaurant", vibe: "Restaurant, Family", time: "11 AM to 10 PM", features: "Tibetan, Chinese, Indian", intensity: 0.7, color: '#FF4500', lat: 30.3471, lng: 78.0471, type: 'restaurant', minZoom: 14 },
  { name: "Doon Darbar", vibe: "Restaurant, Family", time: "11 AM to 11 PM", features: "North Indian, Mughlai", intensity: 0.7, color: '#FF4500', lat: 30.3481, lng: 78.0481, type: 'restaurant', minZoom: 14 },
  { name: "Pind Balluchi", vibe: "Restaurant, Family", time: "11 AM to 10 PM", features: "Punjabi, North Indian", intensity: 0.7, color: '#FF4500', lat: 30.3491, lng: 78.0491, type: 'restaurant', minZoom: 14 },
  { name: "Ginger Restaurant", vibe: "Restaurant, Family", time: "11 AM to 10 PM", features: "Multi-cuisine, Bar", intensity: 0.7, color: '#FF4500', lat: 30.3501, lng: 78.0501, type: 'restaurant', minZoom: 14 },
  { name: "Kalsang Friends Corner", vibe: "Restaurant, Family", time: "9 AM to 9 PM", features: "Tibetan, Chinese, Views", intensity: 0.7, color: '#FF4500', lat: 30.3511, lng: 78.0511, type: 'restaurant', minZoom: 14 }
]; 